// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodInvInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodId        int32                  `protobuf:"varint,1,opt,name=goodId,proto3" json:"goodId,omitempty"` // 商品id
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`       // 库存数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInvInfo) Reset() {
	*x = GoodInvInfo{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInvInfo) ProtoMessage() {}

func (x *GoodInvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInvInfo.ProtoReflect.Descriptor instead.
func (*GoodInvInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GoodInvInfo) GetGoodId() int32 {
	if x != nil {
		return x.GoodId
	}
	return 0
}

func (x *GoodInvInfo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SellInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsInfo     []*GoodInvInfo         `protobuf:"bytes,1,rep,name=goodsInfo,proto3" json:"goodsInfo,omitempty"` // 数组类型，可能会有同时扣减多件商品库存的需求
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInfo) Reset() {
	*x = SellInfo{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInfo) ProtoMessage() {}

func (x *SellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInfo.ProtoReflect.Descriptor instead.
func (*SellInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *SellInfo) GetGoodsInfo() []*GoodInvInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

type MsgTips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTips) Reset() {
	*x = MsgTips{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTips) ProtoMessage() {}

func (x *MsgTips) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTips.ProtoReflect.Descriptor instead.
func (*MsgTips) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *MsgTips) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n" +
	"\vGoodInvInfo\x12\x16\n" +
	"\x06goodId\x18\x01 \x01(\x05R\x06goodId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"6\n" +
	"\bSellInfo\x12*\n" +
	"\tgoodsInfo\x18\x01 \x03(\v2\f.GoodInvInfoR\tgoodsInfo\"\x1b\n" +
	"\aMsgTips\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xae\x01\n" +
	"\tInventory\x12.\n" +
	"\x06SetInv\x12\f.GoodInvInfo\x1a\x16.google.protobuf.Empty\x12'\n" +
	"\tInvDetail\x12\f.GoodInvInfo\x1a\f.GoodInvInfo\x12\x1b\n" +
	"\x04Sell\x12\t.SellInfo\x1a\b.MsgTips\x12+\n" +
	"\x06Reback\x12\t.SellInfo\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_proto_goTypes = []any{
	(*GoodInvInfo)(nil),   // 0: GoodInvInfo
	(*SellInfo)(nil),      // 1: SellInfo
	(*MsgTips)(nil),       // 2: MsgTips
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_inventory_proto_depIdxs = []int32{
	0, // 0: SellInfo.goodsInfo:type_name -> GoodInvInfo
	0, // 1: Inventory.SetInv:input_type -> GoodInvInfo
	0, // 2: Inventory.InvDetail:input_type -> GoodInvInfo
	1, // 3: Inventory.Sell:input_type -> SellInfo
	1, // 4: Inventory.Reback:input_type -> SellInfo
	3, // 5: Inventory.SetInv:output_type -> google.protobuf.Empty
	0, // 6: Inventory.InvDetail:output_type -> GoodInvInfo
	2, // 7: Inventory.Sell:output_type -> MsgTips
	3, // 8: Inventory.Reback:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
